site_name: VSTS Deployment Guide
repo_url: https://github.com/codito/vsts-deploy-guide
theme: readthedocs
pages:
    - Home: index.md
    - Concepts: concepts.md
    - Specify Target Machines: target-machines.md
    - Configure Connections: configure-connections.md
    #- Specify Service Endpoints: service-endpoints.md
    - Deployment Patterns: patterns.md
    - Tasks: tasks.md
    - Contribution Guide: contribute.md
google-analytics: ["UA-66268-8", "vsts-deploy-guide.readthedocs.com"]
